### ISSUE TITLE
Unable to colonize a planet

### ISSUE THREAD

**Issue by skeld** [Gritch69/XG-Project#13]
I've Astrophysics @11, and only 6 planets. Wanted to colonize a new one, but my Colony Ship is going back to the planet where he belong. 
Got a message saying "6". Just "6".

Then i realize there was a huge bug, when the level 11 of astrophysics allow up to 6 planets, and i used to have 6 planets with astrophysics @9 (5 planets according to the table in the skill description)

**Comment by skeld** [comment]
In fact, there's a huge bug somewhere.

**Comment by skeld** [comment]
http://www.les-recycleurs.fr/fr/jeux/mmorpg/gameforge/ogame/tutoriels-ogame/22-tutoriel-cout-de-la-technologie-astrophysique.html

According to this table, Astrophysics level 11 allow for 7 planets. Not 6 as stated in the game.

Nevertheless there's a serious bug somewhere, because even after upgrading two levels of astrophysics i'm unable to colonize a new planet.

**Comment by Gritch69** [comment]
Hello !

I'll investigate on this. By the way, the impacted file is XG-Project/application/libraries/missions/colonize.php.

**Comment by Gritch69** [comment]
Ok, Here's how the check is made:

1. Compute the `max_colonies` = round up of (astrophysics_tech / 2)
2. Store in `planet_count` the total amount of planets minus 1 (because the main planet it's not considered
3. Compare this two variables `if (planet_count => max_colonies) { send error message } else {...}`

So with astrophysics level 11, and 6 planet (check in database), so:

1. `max_colonies` = 6
2. `planet_count` = 6 - 1 = 5
3. Ok... this is not normal

**Comment by Gritch69** [comment]
No problem here.
